back-end/config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "root"
  resources :sessions
  resources :users
  resources :comments
  resources :campaigns do
    resources :todos, only: [:new, :create]
  end
  resources :todos, only: [:destroy]
end

back-end/app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :todos
  has_many :comments, as: :commentable
  validates :title, presence: true
end

back-end/app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authorize
  before_action :expert, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  def index
    @campaigns = Campaign.all
  end

  def show
  end

  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:title, :tags, :estimated_duration, :user_id)
    end
end

back-end/app/helpers/campaigns_helper.rb
module CampaignsHelper
end

back-end/app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags %>
  </div>

  <div class="field">
    <%= form.label :estimated_duration %>
    <%= form.text_field :estimated_duration %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back-end/app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

back-end/app/views/campaigns/index.html.erb
<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tags</th>
      <th>Estimated duration</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.title %></td>
        <td><%= campaign.tags %></td>
        <td><%= campaign.estimated_duration %></td>
        <td><%= campaign.user.try(:email) %></td>
        <td><%= link_to 'Show', campaign %></td>
        <% if current_user.try(:expert?) %>
          <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
          <td><%= link_to 'Destroy', campaign, method: :delete %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if current_user.try(:expert?) %>
  <%= link_to 'New Campaign', new_campaign_path %>
<% end %>

back-end/app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

back-end/app/views/campaigns/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @campaign.title %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @campaign.tags %>
</p>

<p>
  <strong>Estimated duration:</strong>
  <%= @campaign.estimated_duration %>
</p>

<p>
  <strong>User:</strong>
  <%= @campaign.user.try(:email) %>
</p>

<p>
<% if current_user.try(:expert?) %>
  <%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<% end %>
<%= link_to 'Back', campaigns_path %>
</p>

<ul>
  <% @campaign.todos.each do |todo| %>
    <li><%= todo.title %>
      <% if current_user.try(:expert?) %>
        | <%= link_to 'Destroy', todo, method: :delete %></li>
      <% end %>
  <% end %>
</ul>

<p>
<%= link_to 'New Todo', new_campaign_todo_path(@campaign) %>
</p>