back-end/config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "root"
  resources :sessions
  resources :users
  resources :comments
  resources :campaigns do
    resources :todos, only: [:new, :create]
  end
  resources :todos, only: [:destroy]
end

back-end/app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :campaign
  has_many :comments, as: :commentable
  validates :title, presence: true
end

back-end/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :expert, only: [:edit, :update, :destroy]
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def new
    @campaign = Campaign.find params[:campaign_id]
    @todo = Todo.new(campaign: @campaign)
  end

  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to campaign_path(@todo.campaign), notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, @campaign }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to campaign_url(@todo.campaign), notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:title, :campaign_id)
    end
end

back-end/app/helpers/todos_helper.rb
module TodosHelper
end

back-end/app/views/todos/_form.html.erb
<%= form_for([@campaign, @todo]) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.hidden_field :campaign_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

back-end/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |

back-end/app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Campaign</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.campaign %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

back-end/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

back-end/app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @todo.campaign %>
</p>

<!-- <%= link_to 'Edit', edit_todo_path(@todo) %> | -->