back-end/config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: "root"
  resources :sessions
  resources :users
  resources :comments
  resources :campaigns do
    resources :todos, only: [:new, :create]
  end
  resources :todos, only: [:destroy]
end

back-end/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  enum status: %w(qualified not_qualified banned)

  validates :email, presence: true
  validates :email, uniqueness: true

  has_many :campaigns
  belongs_to :role, polymorphic: true, optional: true

  def novice?
    role.nil?
  end

  def expert?
    !novice?
  end

  def type
    return "Novice" if novice?
    "Expert"
  end
end

back-end/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :expert, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end


  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_url, notice: 'Thank you for sign up.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if params[:type] == "Expert" then
      @user.role = ExpertRole.create
    else
      @user.role.destroy
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :username, :status, :role_id)
  end
end

back-end/app/helpers/users_helper.rb
module UsersHelper
end

back-end/app/views/users/edit.html.erb
<h1>Editing Todo</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, required: true %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, User.statuses.keys.to_a %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= select_tag :type, options_for_select(["Expert", "Novice"], @user.type)  %>
  </div>

  <div class="actions"><%= f.submit "Update" %></div>
<% end %>

<p>
<%= link_to 'Show', @user %>
</p>

back-end/app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Username</th>
      <th>Status</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.username %></td>
      <td><%= user.status %></td>
      <td><%= user.type %></td>
      <td><%= link_to 'Show', user %></td>
      <% if current_user.try(:expert?) %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete %></td>
      <% else %>
        <td></td>
        <td></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

back-end/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email, required: true %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

back-end/app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>


<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.type %>
</p>

<% if current_user.try(:expert?) %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>